name: challenges
description: A new Flutter project.
# 다음 줄은 `flutter pub publish`를 사용하여 패키지가 실수로 pub.dev에 게시되는 것을 방지합니다.
# 이는 비공개 패키지의 경우 선호됩니다.
publish_to: none # pub.dev에 게시하려면 이 줄을 제거하십시오.

# 다음은 애플리케이션의 버전 및 빌드 번호를 정의합니다.
# 버전 번호는 1.2.43과 같이 점으로 구분된 세 개의 숫자와 +로 구분된 선택적 빌드 번호로 구성됩니다.
# 버전과 빌드 번호는 각각 --build-name 및 --build-number를 지정하여 플래터 빌드에서 재정의할 수 있습니다.
# Android에서 빌드 이름은 버전 이름으로 사용되며 빌드 번호는 버전 코드로 사용됩니다.
# Android 버전 관리에 대한 자세한 내용은 https://developer.android.com/studio/publish/versioning 에서 확인하세요.
# iOS에서 빌드명은 CFBundleShortVersionString으로 사용되며 빌드번호는 CFBundleVersion으로 사용됩니다.
# iOS 버전 관리에 대한 자세한 내용은
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windows에서 빌드명은 제품 및 파일 버전의 메이저, 마이너, 패치 부분으로 사용되며 빌드번호는 빌드 접미사로 사용됩니다.
version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

# 종속성은 패키지가 작동하기 위해 필요한 다른 패키지를 지정합니다.
# 패키지 종속성을 최신 버전으로 자동 업그레이드하려면 `flutter pub upgrade --major-versions`를 실행합니다.
# 또는 아래 버전 번호를 pub.dev에서 사용 가능한 최신 버전으로 변경하여 종속성을 수동으로 업데이트할 수 있습니다.
# 어떤 종속 요소에 최신 버전이 있는지 확인하려면 `flutter pub outdated`를 실행합니다.
dependencies:
  cupertino_icons: ^1.0.6
  dart_code_metrics: ^4.19.2
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

# 이 파일의 일반 Dart 부분에 대한 자세한 내용은 다음 페이지를 참조하십시오: https://dart.dev/tools/pub/pubspec
# 다음 섹션은 Flutter 패키지에 대한 내용입니다.
flutter:
  # 다음 줄은 머티리얼 아이콘 글꼴이 애플리케이션에 포함되어 있는지 확인하여 머티리얼 아이콘 클래스의 아이콘을 사용할 수 있도록 합니다.
  uses-material-design: true

import_sorter:
  emojis: true

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
  exclude:
    - bin/cache/**
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/gen/*.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/injector.config.dart"
    - "**/test/*.dart"
